// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d9b75cbdeaeee319 "Builtric", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
 * title?: string // Title
 * onjVX49HX0wChange?: any // onjVX49HX0wChange
}} Props

 */
import { routes } from "./chunks/chunk-HMI5HUCM.js";

// virtual:button-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3n473eTzlbh8pfhDK1zg/2pbIDvLUQ7Rn0VvQH2Hr/PWNfioU5L.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	XijSx_UxT: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = [
	"XijSx_UxT",
	"l1MtFmiDP",
	"Efr9UqJyT",
	"P9KxY6lbN",
	"bAsKoULGh",
];
var serializationHash = "framer-wOtpJ";
var variantClassNames = {
	bAsKoULGh: "framer-v-1tqi5zc",
	Efr9UqJyT: "framer-v-13qeelc",
	l1MtFmiDP: "framer-v-16utux",
	P9KxY6lbN: "framer-v-1fm43n7",
	XijSx_UxT: "framer-v-1le3o96",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Default: "XijSx_UxT",
	Disabled: "Efr9UqJyT",
	Error: "bAsKoULGh",
	Loading: "l1MtFmiDP",
	Success: "P9KxY6lbN",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, title, width, ...props }) => {
	return {
		...props,
		jVX49HX0w: title ?? props.jVX49HX0w ?? "Submit",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "XijSx_UxT",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		jVX49HX0w: jVX49HX0w2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "XijSx_UxT",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "l1MtFmiDP") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "l1MtFmiDP") return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.button
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1le3o96",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"XijSx_UxT"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-7eaeceec-39c4-4a6d-bc25-34b9a3c7aa26, rgb(33, 38, 44))",
							borderBottomLeftRadius: 6,
							borderBottomRightRadius: 6,
							borderTopLeftRadius: 6,
							borderTopRightRadius: 6,
							opacity: 1,
							...style,
						}}
						variants={{
							"XijSx_UxT-hover": {
								backgroundColor: "rgb(47, 53, 61)",
								opacity: 1,
							},
							"XijSx_UxT-pressed": {
								backgroundColor: "rgb(26, 29, 33)",
								opacity: 1,
							},
							bAsKoULGh: {
								backgroundColor: "rgba(255, 34, 68, 0.15)",
								opacity: 1,
							},
							Efr9UqJyT: {
								opacity: 0.5,
							},
							P9KxY6lbN: {
								opacity: 1,
							},
						}}
						{...addPropertyOverrides(
							{
								"XijSx_UxT-hover": {
									"data-framer-name": void 0,
								},
								"XijSx_UxT-pressed": {
									"data-framer-name": void 0,
								},
								bAsKoULGh: {
									"data-framer-name": "Error",
								},
								Efr9UqJyT: {
									"data-framer-name": "Disabled",
								},
								l1MtFmiDP: {
									"data-framer-name": "Loading",
								},
								P9KxY6lbN: {
									"data-framer-name": "Success",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-1pihxtd"}
								fonts={["Inter-SemiBold"]}
								layoutDependency={layoutDependency}
								layoutId={"vkNHP7qhX"}
								style={{
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={jVX49HX0w2}
								variants={{
									bAsKoULGh: {
										"--extracted-r6o4lv": "rgb(255, 34, 68)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										bAsKoULGh: {
											children: (
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														dir={"auto"}
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-size": "14px",
															"--framer-font-weight": "600",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 34, 68))",
														}}
													>
														{"Something went wrong"}
													</motion.p>
												</React.Fragment>
											),
											text: void 0,
										},
										P9KxY6lbN: {
											children: (
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														dir={"auto"}
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-size": "14px",
															"--framer-font-weight": "600",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														{"Thank you"}
													</motion.p>
												</React.Fragment>
											),
											text: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										suppressHydrationWarning={true}
										dir={"auto"}
										style={{
											"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
											"--framer-font-weight": "600",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										}}
									>
										{"Submit"}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						{isDisplayed1() && (
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-17f8dxg"}
								data-framer-name={"Spinner"}
								layoutDependency={layoutDependency}
								layoutId={"P6JsEtuwS"}
								style={{
									mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
									WebkitMask:
										"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
								}}
							>
								<MotionDivWithFX
									suppressHydrationWarning={true}
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition2}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-qzr3q9"}
									data-framer-name={"Conic"}
									layoutDependency={layoutDependency}
									layoutId={"bTVm_0qnB"}
									style={{
										background:
											"conic-gradient(from 180deg at 50% 50%, rgb(68, 204, 255) 0deg, rgb(68, 204, 255) 360deg)",
										backgroundColor: "rgb(68, 204, 255)",
										mask: "none",
										WebkitMask: "none",
									}}
									variants={{
										l1MtFmiDP: {
											background:
												"conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
											backgroundColor: "rgba(0, 0, 0, 0)",
											mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
											WebkitMask:
												"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
										},
									}}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-mr3z72"}
										data-framer-name={"Rounding"}
										layoutDependency={layoutDependency}
										layoutId={"LziKEEX3H"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
											borderBottomLeftRadius: 1,
											borderBottomRightRadius: 1,
											borderTopLeftRadius: 1,
											borderTopRightRadius: 1,
										}}
										transformTemplate={transformTemplate1}
									/>
								</MotionDivWithFX>
							</motion.div>
						)}
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-wOtpJ.framer-57w3gf, .framer-wOtpJ .framer-57w3gf { display: block; }",
	".framer-wOtpJ.framer-1le3o96 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 40px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 240px; }",
	".framer-wOtpJ .framer-1pihxtd { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-wOtpJ .framer-17f8dxg { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }",
	".framer-wOtpJ .framer-qzr3q9 { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-wOtpJ .framer-mr3z72 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	".framer-wOtpJ.framer-v-16utux.framer-1le3o96, .framer-wOtpJ.framer-v-13qeelc.framer-1le3o96, .framer-wOtpJ.framer-v-1fm43n7.framer-1le3o96, .framer-wOtpJ.framer-v-1tqi5zc.framer-1le3o96 { cursor: unset; }",
	".framer-wOtpJ.framer-v-16utux .framer-qzr3q9 { overflow: hidden; }",
];
var FramerPWNfioU5L = withCSS(Component, css, "framer-wOtpJ");
var stdin_default = FramerPWNfioU5L;
FramerPWNfioU5L.displayName = "Button 2";
FramerPWNfioU5L.defaultProps = {
	height: 40,
	width: 240,
};
addPropertyControls(FramerPWNfioU5L, {
	variant: {
		options: ["XijSx_UxT", "l1MtFmiDP", "Efr9UqJyT", "P9KxY6lbN", "bAsKoULGh"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
	jVX49HX0w: {
		defaultValue: "Submit",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	onjVX49HX0wChange: {
		changes: "jVX49HX0w",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramerPWNfioU5L,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/yDtI2UI8XcEg1W2je9XPN3Noo.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Button2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_2_default = ComponentWithRoot;
export { button_2_default as default };
