// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d9b75cbdeaeee319 "Builtric", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Mobile' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-K6TVDPUN.js";
import "./chunks/chunk-O4OFXHKJ.js";
import { routes } from "./chunks/chunk-HMI5HUCM.js";

// virtual:demo-ribbon
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/9wODvbNj2sHgcAd5sW2R/VKozH9YxWbN6PkwreR4b/AEHbtwxDA.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/cXekxQOlCNYRCZ5RVtnd/Z6r3wPYWezzCfKlY5jaT/C3C1NK00H.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Archivo-bold",
	"FS;Archivo-bold",
	"FS;Archivo-black italic",
	"FS;Archivo-bold italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Archivo",
				source: "fontshare",
				style: "normal",
				uiFamilyName: "Archivo",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/RJX4LSNI55LNZ6QWGQALARVRCFUYJDBE/HQPW4MP6HXPYZKXF6CFWGJ6ZOJBHKM3X/UHPKREF72UMVMQSKHPDQ42AVOZPICLOJ.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Archivo",
				source: "fontshare",
				style: "italic",
				uiFamilyName: "Archivo",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/6YMFPXTZM4O4CKQMQTPPJXOSPTUX4FAO/ZXIGNMOKJZZB7E6EUWESUAHOSFM2XO7S/XUGABKNP6OBXLKQHWCCIUYO3F7G6VE6C.woff2",
				weight: "900",
			},
			{
				cssFamilyName: "Archivo",
				source: "fontshare",
				style: "italic",
				uiFamilyName: "Archivo",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/KQRPW26V7MQVOVIROFMASPZA32ATHS6D/IXS7QF2ZEPITRFFHZVK6DY26UIO5JY5W/3N3HRVZHDNQLKFXB3E335N7AXAKKO7QL.woff2",
				weight: "700",
			},
		],
	},
];
var css = [
	`.framer-BIgn5 .framer-styles-preset-sj5hvd:not(.rich-text-wrapper), .framer-BIgn5 .framer-styles-preset-sj5hvd.rich-text-wrapper h3 { --framer-font-family: "Archivo", "Archivo Placeholder", sans-serif; --framer-font-family-bold: "Archivo", "Archivo Placeholder", sans-serif; --framer-font-family-bold-italic: "Archivo", sans-serif; --framer-font-family-italic: "Archivo", "Archivo Placeholder", sans-serif; --framer-font-open-type-features: 'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1em; --framer-paragraph-spacing: 18px; --framer-text-alignment: center; --framer-text-background-padding: 0px; --framer-text-color: var(--token-7eaeceec-39c4-4a6d-bc25-34b9a3c7aa26, #21262c); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 820px) { .framer-BIgn5 .framer-styles-preset-sj5hvd:not(.rich-text-wrapper), .framer-BIgn5 .framer-styles-preset-sj5hvd.rich-text-wrapper h3 { --framer-font-family: "Archivo", "Archivo Placeholder", sans-serif; --framer-font-family-bold: "Archivo", "Archivo Placeholder", sans-serif; --framer-font-family-bold-italic: "Archivo", sans-serif; --framer-font-family-italic: "Archivo", "Archivo Placeholder", sans-serif; --framer-font-open-type-features: 'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1em; --framer-paragraph-spacing: 18px; --framer-text-alignment: center; --framer-text-background-padding: 0px; --framer-text-color: var(--token-7eaeceec-39c4-4a6d-bc25-34b9a3c7aa26, #21262c); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 819px) and (min-width: 0px) { .framer-BIgn5 .framer-styles-preset-sj5hvd:not(.rich-text-wrapper), .framer-BIgn5 .framer-styles-preset-sj5hvd.rich-text-wrapper h3 { --framer-font-family: "Archivo", "Archivo Placeholder", sans-serif; --framer-font-family-bold: "Archivo", "Archivo Placeholder", sans-serif; --framer-font-family-bold-italic: "Archivo", sans-serif; --framer-font-family-italic: "Archivo", "Archivo Placeholder", sans-serif; --framer-font-open-type-features: 'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1em; --framer-paragraph-spacing: 18px; --framer-text-alignment: center; --framer-text-background-padding: 0px; --framer-text-color: var(--token-7eaeceec-39c4-4a6d-bc25-34b9a3c7aa26, #21262c); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className = "framer-BIgn5";

// /:https://framerusercontent.com/modules/9wODvbNj2sHgcAd5sW2R/VKozH9YxWbN6PkwreR4b/AEHbtwxDA.js
var ButtonFonts = getFonts(stdin_default);
var cycleOrder = ["MrWGbjUCA", "kZykQkmvq"];
var serializationHash = "framer-csieQ";
var variantClassNames = {
	kZykQkmvq: "framer-v-1thlh72",
	MrWGbjUCA: "framer-v-wn3wau",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "MrWGbjUCA",
	Mobile: "kZykQkmvq",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "MrWGbjUCA",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "MrWGbjUCA",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-wn3wau",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"MrWGbjUCA"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-8969991b-438f-4d85-93dd-14578be35b6e, rgb(255, 219, 52))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								kZykQkmvq: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1lehln5"}
							data-framer-name={"Heading"}
							layoutDependency={layoutDependency}
							layoutId={"ed2bXeJSw"}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-q06ph5"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"BCw25Ewik"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										kZykQkmvq: {
											children: (
												<React.Fragment>
													<motion.h3
														suppressHydrationWarning={true}
														className={"framer-styles-preset-sj5hvd"}
														data-styles-preset={"C3C1NK00H"}
														dir={"auto"}
														style={{
															"--framer-text-alignment": "center",
														}}
													>
														{
															"Ready to bring intelligence to your construction project?"
														}
													</motion.h3>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										suppressHydrationWarning={true}
										className={"framer-styles-preset-sj5hvd"}
										data-styles-preset={"C3C1NK00H"}
										dir={"auto"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{
											"Ready to bring intelligence to your construction project?"
										}
									</motion.h3>
								</React.Fragment>
							</RichText>
							<ResolveLinks
								suppressHydrationWarning={true}
								links={[
									{
										href: {
											webPageId: "UDhHIzXpW",
										},
										implicitPathVariables: void 0,
									},
									{
										href: {
											webPageId: "UDhHIzXpW",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks) => (
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={42}
										width={"212px"}
										y={
											(componentViewport?.y || 0) +
											36 +
											(((componentViewport?.height || 114) - 72 - 42) / 2 +
												0 +
												0) +
											0
										}
										{...addPropertyOverrides(
											{
												kZykQkmvq: {
													y:
														(componentViewport?.y || 0) +
														36 +
														(((componentViewport?.height || 210) - 72 - 90) /
															2 +
															0 +
															0) +
														0 +
														48,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1rthcm9-container"}
											data-framer-name={"Button"}
											layoutDependency={layoutDependency}
											layoutId={"Q2RBX9l7Q-container"}
											name={"Button"}
											nodeId={"Q2RBX9l7Q"}
											rendersWithMotion={true}
											scopeId={"AEHbtwxDA"}
										>
											{_jsx(stdin_default, {
												suppressHydrationWarning: true,
												height: "100%",
												id: "Q2RBX9l7Q",
												layoutId: "Q2RBX9l7Q",
												name: "Button",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: matchVariant("lB1W1EvUp"),
												width: "100%",
												ztBm7NT9R: "Try Now",
												ZUglS10kb: resolvedLinks[0],
												...addPropertyOverrides(
													{
														kZykQkmvq: {
															ZUglS10kb: resolvedLinks[1],
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-csieQ.framer-1jufob1, .framer-csieQ .framer-1jufob1 { display: block; }",
	".framer-csieQ.framer-wn3wau { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 44px; height: min-content; justify-content: center; overflow: hidden; padding: 36px; position: relative; width: 1440px; }",
	".framer-csieQ .framer-1lehln5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-csieQ .framer-q06ph5 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-csieQ .framer-1rthcm9-container { flex: none; height: 42px; position: relative; width: 212px; }",
	".framer-csieQ.framer-v-1thlh72.framer-wn3wau { width: 320px; }",
	".framer-csieQ.framer-v-1thlh72 .framer-1lehln5 { flex-direction: column; }",
	".framer-csieQ.framer-v-1thlh72 .framer-q06ph5 { flex: none; width: 100%; }",
	...css,
];
var FramerAEHbtwxDA = withCSS(Component, css2, "framer-csieQ");
var stdin_default2 = FramerAEHbtwxDA;
FramerAEHbtwxDA.displayName = "Demo Ribbon";
FramerAEHbtwxDA.defaultProps = {
	height: 114,
	width: 1440,
};
addPropertyControls(FramerAEHbtwxDA, {
	variant: {
		options: ["MrWGbjUCA", "kZykQkmvq"],
		optionTitles: ["Variant 1", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerAEHbtwxDA,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerAEHbtwxDA.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:demo-ribbon
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "kZykQkmvq",
	xl: "MrWGbjUCA",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DemoRibbonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var demo_ribbon_default = ComponentWithRoot;
export { demo_ribbon_default as default };
