// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d9b75cbdeaeee319 "Builtric", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone Closed' | 'Phone open' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-KUR7NEVD.js";
import { routes } from "./chunks/chunk-HMI5HUCM.js";

// virtual:links-product
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wAXVXBTYafdmdX3JdaTD/CPq1mRAgEInevsBTORjn/YzNfRSqEF.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var CaretFonts = getFonts(stdin_default);
var cycleOrder = ["RC2XkfluZ", "dElukbY0L", "jlj9506Hb"];
var serializationHash = "framer-q4Tm9";
var variantClassNames = {
	dElukbY0L: "framer-v-101uzoo",
	jlj9506Hb: "framer-v-m2wxsr",
	RC2XkfluZ: "framer-v-521k59",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Phone Closed": "dElukbY0L",
	"Phone open": "jlj9506Hb",
	Desktop: "RC2XkfluZ",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "RC2XkfluZ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RC2XkfluZ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapldw7an = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("jlj9506Hb");
	});
	const onTaphvvg3l = activeVariantCallback(async (...args) => {
		setVariant("dElukbY0L");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["dElukbY0L", "jlj9506Hb"].includes(baseVariant)) return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-521k59",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"RC2XkfluZ"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							borderBottomLeftRadius: 15,
							borderBottomRightRadius: 15,
							borderTopLeftRadius: 15,
							borderTopRightRadius: 15,
							boxShadow: "0px 0px 0px 1px rgba(0, 0, 0, 0.05)",
							...style,
						}}
						variants={{
							dElukbY0L: {
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
								boxShadow: "none",
							},
							jlj9506Hb: {
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
								boxShadow: "none",
							},
						}}
						{...addPropertyOverrides(
							{
								dElukbY0L: {
									"data-framer-name": "Phone Closed",
									"data-highlight": true,
									onTap: onTapldw7an,
								},
								jlj9506Hb: {
									"data-framer-name": "Phone open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-kudcav"}
							layoutDependency={layoutDependency}
							layoutId={"kMGsWxOMH"}
							style={{
								opacity: 1,
							}}
							variants={{
								dElukbY0L: {
									opacity: 0,
								},
								jlj9506Hb: {
									opacity: 1,
								},
							}}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1yr0v62"}
								data-framer-name={"Item"}
								layoutDependency={layoutDependency}
								layoutId={"q3D3Jy_ze"}
							>
								<SVG
									suppressHydrationWarning={true}
									className={"framer-1pg8ao0"}
									data-framer-name={"Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"GEme5H4TL"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><g><defs><path d="M 2 4 C 2 2.895 2.895 2 4 2 L 16 2 C 17.105 2 18 2.895 18 4 L 18 16 C 18 17.105 17.105 18 16 18 L 4 18 C 2.895 18 2 17.105 2 16 Z" id="a1160z"></path><clipPath id="a1161z"><use xlink:href="#a1160z"></use></clipPath></defs><use xlink:href="#a1160z" fill="#eee" clip-path="url(#a1161z)" stroke-width="2" stroke="#ccc"></use></g></svg>'
									}
									svgContentId={9244735573}
									withExternalLayout={true}
								/>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-fyay25"}
									fonts={["Inter-Medium"]}
									layoutDependency={layoutDependency}
									layoutId={"UY8S803ye"}
									style={{
										"--extracted-r6o4lv": "rgb(68, 68, 68)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											style={{
												"--font-selector": "SW50ZXItTWVkaXVt",
												"--framer-font-size": "15px",
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "1.5em",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(68, 68, 68))",
											}}
										>
											{"Procurement"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-ti8pq1"}
								data-framer-name={"Item"}
								layoutDependency={layoutDependency}
								layoutId={"s2smjmhtZ"}
							>
								<SVG
									suppressHydrationWarning={true}
									className={"framer-13mm3ni"}
									data-framer-name={"Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"oImXao4Xo"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><g><defs><path d="M 1 9.975 C 1 5.004 5.029 0.975 10 0.975 L 10 0.975 C 14.971 0.975 19 5.004 19 9.975 L 19 10.025 C 19 14.996 14.971 19.025 10 19.025 L 10 19.025 C 5.029 19.025 1 14.996 1 10.025 Z" id="a1162z"></path><clipPath id="a1163z"><use xlink:href="#a1162z"></use></clipPath></defs><use xlink:href="#a1162z" fill="#eee" clip-path="url(#a1163z)" stroke-width="2" stroke="#ccc"></use></g></svg>'
									}
									svgContentId={12810902438}
									withExternalLayout={true}
								/>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-11hwsbq"}
									fonts={["Inter-Medium"]}
									layoutDependency={layoutDependency}
									layoutId={"ynOd9JsF5"}
									style={{
										"--extracted-r6o4lv": "rgb(68, 68, 68)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											style={{
												"--font-selector": "SW50ZXItTWVkaXVt",
												"--framer-font-size": "15px",
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "1.5em",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(68, 68, 68))",
											}}
										>
											{"Finance"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-5kh50a"}
								data-framer-name={"Item"}
								layoutDependency={layoutDependency}
								layoutId={"Omb6plNmG"}
							>
								<SVG
									suppressHydrationWarning={true}
									className={"framer-13wrqhc"}
									data-framer-name={"Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"aqclQIsUz"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><g><defs><path d="M 8.293 2.293 C 9.073 1.016 10.927 1.016 11.707 2.293 L 19.14 14.457 C 19.955 15.79 18.996 17.5 17.434 17.5 L 2.566 17.5 C 1.004 17.5 0.045 15.79 0.86 14.457 Z" id="a1164z"></path><clipPath id="a1165z"><use xlink:href="#a1164z"></use></clipPath></defs><use xlink:href="#a1164z" fill="#eee" clip-path="url(#a1165z)" stroke-width="2" stroke="#ccc"></use></g></svg>'
									}
									svgContentId={9486151537}
									withExternalLayout={true}
								/>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1trttn3"}
									fonts={["Inter-Medium"]}
									layoutDependency={layoutDependency}
									layoutId={"fYYlJpdoR"}
									style={{
										"--extracted-r6o4lv": "rgb(68, 68, 68)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											style={{
												"--font-selector": "SW50ZXItTWVkaXVt",
												"--framer-font-size": "15px",
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "1.5em",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(68, 68, 68))",
											}}
										>
											{"Project Management"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-esz379"}
								data-framer-name={"Item"}
								layoutDependency={layoutDependency}
								layoutId={"ciqt9a7ZY"}
							>
								<SVG
									suppressHydrationWarning={true}
									className={"framer-4imjon"}
									data-framer-name={"Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"uQZnRDXNB"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><g><defs><path d="M 8.293 2.293 C 9.073 1.016 10.927 1.016 11.707 2.293 L 19.14 14.457 C 19.955 15.79 18.996 17.5 17.434 17.5 L 2.566 17.5 C 1.004 17.5 0.045 15.79 0.86 14.457 Z" id="a1164z"></path><clipPath id="a1165z"><use xlink:href="#a1164z"></use></clipPath></defs><use xlink:href="#a1164z" fill="#eee" clip-path="url(#a1165z)" stroke-width="2" stroke="#ccc"></use></g></svg>'
									}
									svgContentId={9486151537}
									withExternalLayout={true}
								/>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-9ilw2x"}
									fonts={["Inter-Medium"]}
									layoutDependency={layoutDependency}
									layoutId={"Pae14HAEg"}
									style={{
										"--extracted-r6o4lv": "rgb(68, 68, 68)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											style={{
												"--font-selector": "SW50ZXItTWVkaXVt",
												"--framer-font-size": "15px",
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "1.5em",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(68, 68, 68))",
											}}
										>
											{"HSE Management"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-111dk8"}
								data-framer-name={"Item"}
								layoutDependency={layoutDependency}
								layoutId={"zrkJtJpvc"}
							>
								<SVG
									suppressHydrationWarning={true}
									className={"framer-12vltqr"}
									data-framer-name={"Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"IIjjELpby"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><g><defs><path d="M 8.293 2.293 C 9.073 1.016 10.927 1.016 11.707 2.293 L 19.14 14.457 C 19.955 15.79 18.996 17.5 17.434 17.5 L 2.566 17.5 C 1.004 17.5 0.045 15.79 0.86 14.457 Z" id="a1164z"></path><clipPath id="a1165z"><use xlink:href="#a1164z"></use></clipPath></defs><use xlink:href="#a1164z" fill="#eee" clip-path="url(#a1165z)" stroke-width="2" stroke="#ccc"></use></g></svg>'
									}
									svgContentId={9486151537}
									withExternalLayout={true}
								/>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-7vdnrx"}
									fonts={["Inter-Medium"]}
									layoutDependency={layoutDependency}
									layoutId={"SgAEZQeZA"}
									style={{
										"--extracted-r6o4lv": "rgb(68, 68, 68)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											style={{
												"--font-selector": "SW50ZXItTWVkaXVt",
												"--framer-font-size": "15px",
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "1.5em",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(68, 68, 68))",
											}}
										>
											{"Data Management"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1j09mjo"}
								data-framer-name={"Solutions"}
								layoutDependency={layoutDependency}
								layoutId={"AeXslBQWS"}
								{...addPropertyOverrides(
									{
										jlj9506Hb: {
											"data-highlight": true,
											onTap: onTaphvvg3l,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-6mjkti"}
									layoutDependency={layoutDependency}
									layoutId={"ksIJBaJzy"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-14nu2b2"}
										fonts={["Inter-Medium"]}
										layoutDependency={layoutDependency}
										layoutId={"DCOFp2SRZ"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												style={{
													"--font-selector": "SW50ZXItTWVkaXVt",
													"--framer-font-size": "15px",
													"--framer-font-weight": "500",
												}}
											>
												{"Solutions"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<ComponentViewportProvider suppressHydrationWarning={true}>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1xxiwqq-container"}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"IjVYdtC4I-container"}
											nodeId={"IjVYdtC4I"}
											rendersWithMotion={true}
											scopeId={"YzNfRSqEF"}
										>
											{_jsx(stdin_default, {
												suppressHydrationWarning: true,
												height: "100%",
												id: "IjVYdtC4I",
												layoutId: "IjVYdtC4I",
												variant: matchVariant("wnipua7N_"),
												width: "100%",
												...addPropertyOverrides(
													{
														jlj9506Hb: {
															variant: matchVariant("BJYJhvClj"),
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-u7v6pw"}
									layoutDependency={layoutDependency}
									layoutId={"u21zgXehv"}
									style={{
										backgroundColor: "rgb(238, 238, 238)",
									}}
								/>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-q4Tm9.framer-1ycnoe0, .framer-q4Tm9 .framer-1ycnoe0 { display: block; }",
	".framer-q4Tm9.framer-521k59 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; padding: 15px; position: relative; width: 267px; }",
	".framer-q4Tm9 .framer-kudcav { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-q4Tm9 .framer-1yr0v62, .framer-q4Tm9 .framer-ti8pq1, .framer-q4Tm9 .framer-5kh50a, .framer-q4Tm9 .framer-esz379, .framer-q4Tm9 .framer-111dk8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-q4Tm9 .framer-1pg8ao0, .framer-q4Tm9 .framer-13mm3ni, .framer-q4Tm9 .framer-13wrqhc, .framer-q4Tm9 .framer-4imjon, .framer-q4Tm9 .framer-12vltqr { flex: none; height: 20px; position: relative; width: 20px; }",
	".framer-q4Tm9 .framer-fyay25, .framer-q4Tm9 .framer-11hwsbq, .framer-q4Tm9 .framer-1trttn3, .framer-q4Tm9 .framer-9ilw2x, .framer-q4Tm9 .framer-7vdnrx { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-q4Tm9 .framer-1j09mjo { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 32px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-q4Tm9 .framer-6mjkti { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: 15px; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-q4Tm9 .framer-14nu2b2 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-q4Tm9 .framer-1xxiwqq-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-q4Tm9 .framer-u7v6pw { flex: none; height: 1px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; }",
	".framer-q4Tm9.framer-v-101uzoo.framer-521k59 { cursor: pointer; gap: 0px; overflow: hidden; padding: 12px 0px 0px 0px; }",
	".framer-q4Tm9.framer-v-101uzoo .framer-kudcav { height: 0px; justify-content: flex-start; order: 2; overflow: hidden; }",
	".framer-q4Tm9.framer-v-101uzoo .framer-1j09mjo { order: 0; }",
	".framer-q4Tm9.framer-v-m2wxsr.framer-521k59 { gap: 15px; padding: 12px 0px 0px 0px; }",
	".framer-q4Tm9.framer-v-m2wxsr .framer-kudcav { gap: 27px; justify-content: flex-start; order: 2; padding: 0px 0px 24px 0px; }",
	".framer-q4Tm9.framer-v-m2wxsr .framer-1j09mjo { cursor: pointer; order: 0; }",
];
var FramerYzNfRSqEF = withCSS(Component, css, "framer-q4Tm9");
var stdin_default2 = FramerYzNfRSqEF;
FramerYzNfRSqEF.displayName = "Links: Product";
FramerYzNfRSqEF.defaultProps = {
	height: 182,
	width: 267,
};
addPropertyControls(FramerYzNfRSqEF, {
	variant: {
		options: ["RC2XkfluZ", "dElukbY0L", "jlj9506Hb"],
		optionTitles: ["Desktop", "Phone Closed", "Phone open"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerYzNfRSqEF,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
			],
		},
		...CaretFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerYzNfRSqEF.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:links-product
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LinksProductFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var links_product_default = ComponentWithRoot;
export { links_product_default as default };
