// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d9b75cbdeaeee319 "Builtric", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * required?: boolean // Required
 * gap?: number // Gap
 * padding?: string // Padding
 * font?: any // Font
 * inputBG?: string // Input BG
 * inputText?: string // Input Text
 * valueTextColor?: string // Value Text Color
 * optionBG?: string // Option BG
 * optionText?: string // Option Text
 * border?: string // Border
 * radius?: number // Radius
 * radiusInner?: number // Radius Inner
 * focus?: string // Focus
 * focusBackground?: string // Focus Background
 * dropdownSelected?: string // Dropdown Selected
 * dropdownText?: string // Dropdown Text
 * dropdownSelectedText?: string // Dropdown Selected Text
 * defaultCountry?: '🇺🇸 United States +1' | '🇨🇦 Canada +1' | '🇲🇽 Mexico +52' | '🇧🇷 Brazil +55' | '🇦🇷 Argentina +54' | '🇨🇱 Chile +56' | '🇨🇴 Colombia +57' | '🇵🇪 Peru +51' | '🇬🇧 United Kingdom +44' | '🇮🇪 Ireland +353' | '🇫🇷 France +33' | '🇩🇪 Germany +49' | '🇪🇸 Spain +34' | '🇮🇹 Italy +39' | '🇳🇱 Netherlands +31' | '🇧🇪 Belgium +32' | '🇨🇭 Switzerland +41' | '🇦🇹 Austria +43' | '🇸🇪 Sweden +46' | '🇳🇴 Norway +47' | '🇩🇰 Denmark +45' | '🇫🇮 Finland +358' | '🇵🇱 Poland +48' | '🇨🇿 Czechia +420' | '🇭🇺 Hungary +36' | '🇷🇴 Romania +40' | '🇬🇷 Greece +30' | '🇵🇹 Portugal +351' | '🇸🇰 Slovakia +421' | '🇺🇦 Ukraine +380' | '🇹🇷 Turkey +90' | '🇮🇱 Israel +972' | '🇸🇦 Saudi Arabia +966' | '🇦🇪 United Arab Emirates +971' | '🇪🇬 Egypt +20' | '🇿🇦 South Africa +27' | '🇳🇬 Nigeria +234' | '🇰🇪 Kenya +254' | '🇮🇳 India +91' | '🇵🇰 Pakistan +92' | '🇧🇩 Bangladesh +880' | '🇨🇳 China +86' | '🇯🇵 Japan +81' | '🇰🇷 South Korea +82' | '🇸🇬 Singapore +65' | '🇲🇾 Malaysia +60' | '🇹🇭 Thailand +66' | '🇻🇳 Vietnam +84' | '🇮🇩 Indonesia +62' | '🇵🇭 Philippines +63' | '🇦🇺 Australia +61' | '🇳🇿 New Zealand +64' // Default Country
 * placeholder?: string // Placeholder
 * inputARIALabel?: string // Input ARIA Label
 * selectARIALabel?: string // Select ARIA Label
 * customCountries?: boolean // Custom Countries
 * cSVFile?: string // CSV File
}} Props

 */
import { routes } from "./chunks/chunk-HMI5HUCM.js";

// virtual:phone-number-input
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/D5maVtlZR76AoGctcwS0/N5jbfJlnAmmY0vqsaxTK/PhoneNumberInput.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useMemo, useRef, useEffect, startTransition } from "react";
import { addPropertyControls, ControlType } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var countries = [
	{
		code: "US",
		name: "United States",
		prefix: "+1",
		flag: "\u{1F1FA}\u{1F1F8}",
	},
	{
		code: "CA",
		name: "Canada",
		prefix: "+1",
		flag: "\u{1F1E8}\u{1F1E6}",
	},
	{
		code: "MX",
		name: "Mexico",
		prefix: "+52",
		flag: "\u{1F1F2}\u{1F1FD}",
	},
	{
		code: "BR",
		name: "Brazil",
		prefix: "+55",
		flag: "\u{1F1E7}\u{1F1F7}",
	},
	{
		code: "AR",
		name: "Argentina",
		prefix: "+54",
		flag: "\u{1F1E6}\u{1F1F7}",
	},
	{
		code: "CL",
		name: "Chile",
		prefix: "+56",
		flag: "\u{1F1E8}\u{1F1F1}",
	},
	{
		code: "CO",
		name: "Colombia",
		prefix: "+57",
		flag: "\u{1F1E8}\u{1F1F4}",
	},
	{
		code: "PE",
		name: "Peru",
		prefix: "+51",
		flag: "\u{1F1F5}\u{1F1EA}",
	},
	{
		code: "GB",
		name: "United Kingdom",
		prefix: "+44",
		flag: "\u{1F1EC}\u{1F1E7}",
	},
	{
		code: "IE",
		name: "Ireland",
		prefix: "+353",
		flag: "\u{1F1EE}\u{1F1EA}",
	},
	{
		code: "FR",
		name: "France",
		prefix: "+33",
		flag: "\u{1F1EB}\u{1F1F7}",
	},
	{
		code: "DE",
		name: "Germany",
		prefix: "+49",
		flag: "\u{1F1E9}\u{1F1EA}",
	},
	{
		code: "ES",
		name: "Spain",
		prefix: "+34",
		flag: "\u{1F1EA}\u{1F1F8}",
	},
	{
		code: "IT",
		name: "Italy",
		prefix: "+39",
		flag: "\u{1F1EE}\u{1F1F9}",
	},
	{
		code: "NL",
		name: "Netherlands",
		prefix: "+31",
		flag: "\u{1F1F3}\u{1F1F1}",
	},
	{
		code: "BE",
		name: "Belgium",
		prefix: "+32",
		flag: "\u{1F1E7}\u{1F1EA}",
	},
	{
		code: "CH",
		name: "Switzerland",
		prefix: "+41",
		flag: "\u{1F1E8}\u{1F1ED}",
	},
	{
		code: "AT",
		name: "Austria",
		prefix: "+43",
		flag: "\u{1F1E6}\u{1F1F9}",
	},
	{
		code: "SE",
		name: "Sweden",
		prefix: "+46",
		flag: "\u{1F1F8}\u{1F1EA}",
	},
	{
		code: "NO",
		name: "Norway",
		prefix: "+47",
		flag: "\u{1F1F3}\u{1F1F4}",
	},
	{
		code: "DK",
		name: "Denmark",
		prefix: "+45",
		flag: "\u{1F1E9}\u{1F1F0}",
	},
	{
		code: "FI",
		name: "Finland",
		prefix: "+358",
		flag: "\u{1F1EB}\u{1F1EE}",
	},
	{
		code: "PL",
		name: "Poland",
		prefix: "+48",
		flag: "\u{1F1F5}\u{1F1F1}",
	},
	{
		code: "CZ",
		name: "Czechia",
		prefix: "+420",
		flag: "\u{1F1E8}\u{1F1FF}",
	},
	{
		code: "HU",
		name: "Hungary",
		prefix: "+36",
		flag: "\u{1F1ED}\u{1F1FA}",
	},
	{
		code: "RO",
		name: "Romania",
		prefix: "+40",
		flag: "\u{1F1F7}\u{1F1F4}",
	},
	{
		code: "GR",
		name: "Greece",
		prefix: "+30",
		flag: "\u{1F1EC}\u{1F1F7}",
	},
	{
		code: "PT",
		name: "Portugal",
		prefix: "+351",
		flag: "\u{1F1F5}\u{1F1F9}",
	},
	{
		code: "SK",
		name: "Slovakia",
		prefix: "+421",
		flag: "\u{1F1F8}\u{1F1F0}",
	},
	{
		code: "UA",
		name: "Ukraine",
		prefix: "+380",
		flag: "\u{1F1FA}\u{1F1E6}",
	},
	{
		code: "TR",
		name: "Turkey",
		prefix: "+90",
		flag: "\u{1F1F9}\u{1F1F7}",
	},
	{
		code: "IL",
		name: "Israel",
		prefix: "+972",
		flag: "\u{1F1EE}\u{1F1F1}",
	},
	{
		code: "SA",
		name: "Saudi Arabia",
		prefix: "+966",
		flag: "\u{1F1F8}\u{1F1E6}",
	},
	{
		code: "AE",
		name: "United Arab Emirates",
		prefix: "+971",
		flag: "\u{1F1E6}\u{1F1EA}",
	},
	{
		code: "EG",
		name: "Egypt",
		prefix: "+20",
		flag: "\u{1F1EA}\u{1F1EC}",
	},
	{
		code: "ZA",
		name: "South Africa",
		prefix: "+27",
		flag: "\u{1F1FF}\u{1F1E6}",
	},
	{
		code: "NG",
		name: "Nigeria",
		prefix: "+234",
		flag: "\u{1F1F3}\u{1F1EC}",
	},
	{
		code: "KE",
		name: "Kenya",
		prefix: "+254",
		flag: "\u{1F1F0}\u{1F1EA}",
	},
	{
		code: "IN",
		name: "India",
		prefix: "+91",
		flag: "\u{1F1EE}\u{1F1F3}",
	},
	{
		code: "PK",
		name: "Pakistan",
		prefix: "+92",
		flag: "\u{1F1F5}\u{1F1F0}",
	},
	{
		code: "BD",
		name: "Bangladesh",
		prefix: "+880",
		flag: "\u{1F1E7}\u{1F1E9}",
	},
	{
		code: "CN",
		name: "China",
		prefix: "+86",
		flag: "\u{1F1E8}\u{1F1F3}",
	},
	{
		code: "JP",
		name: "Japan",
		prefix: "+81",
		flag: "\u{1F1EF}\u{1F1F5}",
	},
	{
		code: "KR",
		name: "South Korea",
		prefix: "+82",
		flag: "\u{1F1F0}\u{1F1F7}",
	},
	{
		code: "SG",
		name: "Singapore",
		prefix: "+65",
		flag: "\u{1F1F8}\u{1F1EC}",
	},
	{
		code: "MY",
		name: "Malaysia",
		prefix: "+60",
		flag: "\u{1F1F2}\u{1F1FE}",
	},
	{
		code: "TH",
		name: "Thailand",
		prefix: "+66",
		flag: "\u{1F1F9}\u{1F1ED}",
	},
	{
		code: "VN",
		name: "Vietnam",
		prefix: "+84",
		flag: "\u{1F1FB}\u{1F1F3}",
	},
	{
		code: "ID",
		name: "Indonesia",
		prefix: "+62",
		flag: "\u{1F1EE}\u{1F1E9}",
	},
	{
		code: "PH",
		name: "Philippines",
		prefix: "+63",
		flag: "\u{1F1F5}\u{1F1ED}",
	},
	{
		code: "AU",
		name: "Australia",
		prefix: "+61",
		flag: "\u{1F1E6}\u{1F1FA}",
	},
	{
		code: "NZ",
		name: "New Zealand",
		prefix: "+64",
		flag: "\u{1F1F3}\u{1F1FF}",
	},
];
function parseCSV(csvContent) {
	try {
		const lines = csvContent.trim().split("\n");
		const headers = lines[0].split(",").map((h) => h.trim().toLowerCase());
		const codeIndex = headers.findIndex((h) => h.includes("code"));
		const nameIndex = headers.findIndex((h) => h.includes("name"));
		const prefixIndex = headers.findIndex((h) => h.includes("prefix"));
		const flagIndex = headers.findIndex((h) => h.includes("flag"));
		if (codeIndex === -1 || nameIndex === -1 || prefixIndex === -1)
			return countries;
		const parsed = [];
		for (let i = 1; i < lines.length; i++) {
			const values = lines[i].split(",").map((v) => v.trim().replace(/"/g, ""));
			parsed.push({
				code: values[codeIndex] || `C${i}`,
				name: values[nameIndex] || "Unknown",
				prefix: values[prefixIndex] || "+1",
				flag: flagIndex !== -1 ? values[flagIndex] : "\u{1F3F3}\uFE0F",
			});
		}
		return parsed.length ? parsed : countries;
	} catch {
		return countries;
	}
}
function getCountryByCode(code, list) {
	return list.find((c) => c.code === code) || list[0];
}
function PhoneNumberInput(props) {
	const {
		font,
		inputBackground,
		inputTextColor,
		valueTextColor,
		optionBackground,
		optionTextColor,
		borderColor,
		borderRadius,
		radiusInner,
		focusColor,
		dropdownSelectedColor,
		dropdownTextColor,
		dropdownSelectedTextColor,
		focusBackground,
		defaultCountry,
		placeholder,
		required,
		style,
		ariaLabelInput,
		ariaLabelSelect,
		useCustomCSV,
		csvFile = "https://framerusercontent.com/assets/8w3IUatLX9a5JVJ6XPCVuHi94.mp3",
		gap,
		fieldPadding,
		...rest
	} = props;
	const [customCountries, setCustomCountries] = useState(countries);
	const [csvLoaded, setCsvLoaded] = useState(false);
	const [initialCountrySet, setInitialCountrySet] = useState(false);
	useEffect(() => {
		if (useCustomCSV && csvFile && !csvLoaded) {
			fetch(csvFile)
				.then((res) => res.text())
				.then((csv) => {
					const parsed = parseCSV(csv);
					startTransition(() => {
						setCustomCountries(parsed);
						setCsvLoaded(true);
					});
				})
				.catch(() => startTransition(() => setCustomCountries(countries)));
		} else if (!useCustomCSV) {
			startTransition(() => {
				setCustomCountries(countries);
				setCsvLoaded(false);
			});
		}
	}, [useCustomCSV, csvFile, csvLoaded]);
	const activeCountries = useCustomCSV ? customCountries : countries;
	const [phone, setPhone] = useState("");
	const [selectedCountry, setSelectedCountry] = useState(
		getCountryByCode(defaultCountry, activeCountries),
	);
	const [dropdownOpen, setDropdownOpen] = useState(false);
	const [filter, setFilter] = useState("");
	const [highlighted, setHighlighted] = useState(0);
	const [inputFocused, setInputFocused] = useState(false);
	const [selectFocused, setSelectFocused] = useState(false);
	const inputRef = useRef(null);
	const selectRef = useRef(null);
	const dropdownRef = useRef(null);
	useEffect(() => {
		if (typeof document === "undefined") return;
		function handleClickOutside(event) {
			if (selectRef.current && !selectRef.current.contains(event.target)) {
				startTransition(() => setDropdownOpen(false));
			}
		}
		if (dropdownOpen) {
			document.addEventListener("mousedown", handleClickOutside);
			return () =>
				document.removeEventListener("mousedown", handleClickOutside);
		}
	}, [dropdownOpen]);
	useEffect(() => {
		if (!initialCountrySet && activeCountries.length) {
			startTransition(() => {
				setSelectedCountry(getCountryByCode(defaultCountry, activeCountries));
				setInitialCountrySet(true);
			});
		}
	}, [activeCountries, defaultCountry, initialCountrySet]);
	const filteredCountries = useMemo(() => {
		if (!filter) return activeCountries;
		return activeCountries.filter((c) =>
			c.name.toLowerCase().includes(filter.toLowerCase()),
		);
	}, [filter, activeCountries]);
	useEffect(() => {
		if (!props.onValueChange) return;
		const nextValue = required
			? selectedCountry.prefix + (phone || "")
			: phone
				? selectedCountry.prefix + phone
				: "";
		props.onValueChange(nextValue);
	}, [phone, selectedCountry, required]);
	const isMobile =
		typeof __unframerWindow !== "undefined" &&
		__unframerWindow.innerWidth < 600;
	const baseFont = {
		fontFamily: "inherit",
		fontSize: 16,
		lineHeight: 1.3,
	};
	const inputStyles = {
		...baseFont,
		...font,
		background: inputFocused ? focusBackground : inputBackground,
		color: valueTextColor,
		border: `1px solid ${inputFocused ? focusColor : borderColor}`,
		borderRadius,
		outline: "none",
		padding: fieldPadding,
		flex: 1,
		minWidth: 0,
		width: "100%",
		boxSizing: "border-box",
		transition: "border-color 0.2s, background 0.2s",
	};
	const selectStyles = {
		...baseFont,
		...font,
		background: selectFocused ? focusBackground : inputBackground,
		color: inputTextColor,
		border: `1px solid ${selectFocused ? focusColor : borderColor}`,
		borderRadius,
		outline: "none",
		padding: fieldPadding,
		minWidth: 0,
		display: "flex",
		alignItems: "center",
		cursor: "pointer",
		gap: 8,
		transition: "border-color 0.2s, background 0.2s",
		userSelect: "none",
		width: isMobile ? "100%" : 120,
		position: "relative",
	};
	const dropdownStyles = {
		position: "absolute",
		top: "100%",
		left: 0,
		width: 240,
		background: optionBackground,
		color: optionTextColor,
		border: `1px solid ${borderColor}`,
		borderRadius,
		zIndex: 1e3,
		height: 240,
		overflowY: "auto",
		boxShadow: "0 4px 16px rgba(0,0,0,0.08)",
		marginTop: 4,
		padding: "2px",
	};
	const optionStyles = (active) => ({
		...baseFont,
		...font,
		display: "flex",
		alignItems: "center",
		gap: 8,
		padding: "12px 16px",
		height: "48px",
		background: active ? dropdownSelectedColor : optionBackground,
		color: active ? dropdownSelectedTextColor : dropdownTextColor,
		fontWeight: 400,
		cursor: "pointer",
		borderRadius: active ? radiusInner : 0,
	});
	return (
		<div
			suppressHydrationWarning={true}
			style={{
				...style,
				width: "100%",
				minWidth: 0,
				display: "flex",
				flexDirection: isMobile ? "column" : "row",
				gap,
				alignItems: "stretch",
				position: "relative",
			}}
		>
			<div
				suppressHydrationWarning={true}
				ref={selectRef}
				tabIndex={0}
				aria-label={ariaLabelSelect || "Country code selector"}
				aria-haspopup={"listbox"}
				aria-expanded={dropdownOpen}
				style={selectStyles}
				onClick={() => startTransition(() => setDropdownOpen((v) => !v))}
				onKeyDown={(e) => {
					if (["Enter", " ", "ArrowDown"].includes(e.key))
						startTransition(() => setDropdownOpen(true));
				}}
				onFocus={() => startTransition(() => setSelectFocused(true))}
				onBlur={(e) => {
					if (!e.currentTarget.contains(e.relatedTarget))
						startTransition(() => setSelectFocused(false));
				}}
				role={"combobox"}
				aria-controls={"country-listbox"}
			>
				<span
					suppressHydrationWarning={true}
					style={{
						fontSize: 18,
					}}
				>
					{selectedCountry.flag}
				</span>
				<span suppressHydrationWarning={true}>{selectedCountry.prefix}</span>
				{dropdownOpen && (
					<div
						suppressHydrationWarning={true}
						ref={dropdownRef}
						style={dropdownStyles}
						id={"country-listbox"}
						role={"listbox"}
					>
						<input
							suppressHydrationWarning={true}
							autoFocus={true}
							type={"text"}
							placeholder={"Type to filter\u2026"}
							value={filter}
							onChange={(e) => {
								const next = e.target.value;
								startTransition(() => {
									setFilter(next);
									setHighlighted(0);
								});
							}}
							onKeyDown={(e) => {
								if (e.key === "ArrowDown") {
									e.preventDefault();
									startTransition(() => {
										setHighlighted((prev) =>
											prev < filteredCountries.length - 1 ? prev + 1 : 0,
										);
									});
								} else if (e.key === "ArrowUp") {
									e.preventDefault();
									startTransition(() => {
										setHighlighted((prev) =>
											prev > 0 ? prev - 1 : filteredCountries.length - 1,
										);
									});
								} else if (
									e.key === "Enter" &&
									filteredCountries[highlighted]
								) {
									e.preventDefault();
									e.stopPropagation();
									const selectedCountryItem = filteredCountries[highlighted];
									startTransition(() => {
										setSelectedCountry(selectedCountryItem);
										setDropdownOpen(false);
										setFilter("");
										setHighlighted(0);
									});
									setTimeout(() => selectRef.current?.focus(), 0);
								} else if (e.key === "Escape") {
									e.preventDefault();
									startTransition(() => {
										setDropdownOpen(false);
										setFilter("");
										setHighlighted(0);
									});
									setTimeout(() => selectRef.current?.focus(), 0);
								}
							}}
							style={{
								...baseFont,
								...font,
								width: "100%",
								boxSizing: "border-box",
								padding: fieldPadding,
								border: "none",
								outline: "none",
								background: optionBackground,
								color: valueTextColor,
								marginBottom: 2,
								borderRadius: `${radiusInner}px ${radiusInner}px 0 0`,
								lineHeight: "1.5em",
							}}
							aria-label={"Filter countries"}
						/>
						{filteredCountries.length === 0 && (
							<div
								suppressHydrationWarning={true}
								style={{
									padding: 12,
									color: "#888",
								}}
							>
								{"No countries found"}
							</div>
						)}
						{filteredCountries.map((c, i) => (
							<div
								suppressHydrationWarning={true}
								style={optionStyles(i === highlighted)}
								role={"option"}
								aria-selected={i === highlighted}
								tabIndex={-1}
								onMouseEnter={() => startTransition(() => setHighlighted(i))}
								onMouseDown={() => {
									startTransition(() => {
										setSelectedCountry(c);
										setDropdownOpen(false);
										setFilter("");
										setHighlighted(0);
									});
									selectRef.current?.focus();
								}}
							>
								<span
									suppressHydrationWarning={true}
									style={{
										fontSize: 18,
										marginRight: 6,
									}}
								>
									{c.flag}
								</span>
								<span
									suppressHydrationWarning={true}
									style={{
										flex: 1,
										minWidth: 0,
										whiteSpace: "nowrap",
										overflow: "hidden",
										textOverflow: "ellipsis",
									}}
								>
									{c.name}
								</span>
								<span
									suppressHydrationWarning={true}
									style={{
										fontWeight: 400,
										marginLeft: 6,
										color: valueTextColor,
									}}
								>
									{c.prefix}
								</span>
							</div>
						))}
					</div>
				)}
			</div>
			<input
				suppressHydrationWarning={true}
				ref={inputRef}
				type={"tel"}
				aria-label={ariaLabelInput || "Phone number input"}
				style={inputStyles}
				placeholder={placeholder}
				value={phone}
				onChange={(e) => {
					const next = e.target.value;
					startTransition(() => setPhone(next));
				}}
				autoComplete={"tel"}
				inputMode={"tel"}
				pattern={"[0-9\\s\\-]*"}
				required={required}
				onFocus={() => startTransition(() => setInputFocused(true))}
				onBlur={() => startTransition(() => setInputFocused(false))}
				formNoValidate={true}
			/>
			<input
				suppressHydrationWarning={true}
				type={"hidden"}
				name={"Phone"}
				value={
					required
						? selectedCountry.prefix + (phone || "")
						: phone
							? selectedCountry.prefix + phone
							: ""
				}
			/>
		</div>
	);
}
addPropertyControls(PhoneNumberInput, {
	required: {
		type: ControlType.Boolean,
		title: "Required",
		defaultValue: false,
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	gap: {
		type: ControlType.Number,
		title: "Gap",
		defaultValue: 10,
		min: 0,
		max: 50,
		unit: "px",
	},
	fieldPadding: {
		type: ControlType.String,
		title: "Padding",
		defaultValue: "12px 16px",
	},
	font: {
		type: ControlType.Font,
		title: "Font",
		defaultValue: {
			fontSize: 16,
			variant: "Regular",
			letterSpacing: "-0.01em",
			lineHeight: "1.3em",
		},
		controls: "extended",
		defaultFontType: "sans-serif",
	},
	inputBackground: {
		type: ControlType.Color,
		title: "Input BG",
		defaultValue: "#FFFFFF",
	},
	inputTextColor: {
		type: ControlType.Color,
		title: "Input Text",
		defaultValue: "#000000",
	},
	valueTextColor: {
		type: ControlType.Color,
		title: "Value Text Color",
		defaultValue: "#000000",
	},
	optionBackground: {
		type: ControlType.Color,
		title: "Option BG",
		defaultValue: "#FFFFFF",
	},
	optionTextColor: {
		type: ControlType.Color,
		title: "Option Text",
		defaultValue: "#000000",
	},
	borderColor: {
		type: ControlType.Color,
		title: "Border",
		defaultValue: "#EEEEEE",
	},
	borderRadius: {
		type: ControlType.Number,
		title: "Radius",
		defaultValue: 8,
		min: 0,
		max: 32,
	},
	radiusInner: {
		type: ControlType.Number,
		title: "Radius Inner",
		defaultValue: 6,
		min: 0,
		max: 32,
	},
	focusColor: {
		type: ControlType.Color,
		title: "Focus",
		defaultValue: "#0099FF",
	},
	focusBackground: {
		type: ControlType.Color,
		title: "Focus Background",
		defaultValue: "#F5F5F5",
	},
	dropdownSelectedColor: {
		type: ControlType.Color,
		title: "Dropdown Selected",
		defaultValue: "#000000",
	},
	dropdownTextColor: {
		type: ControlType.Color,
		title: "Dropdown Text",
		defaultValue: "#999999",
	},
	dropdownSelectedTextColor: {
		type: ControlType.Color,
		title: "Dropdown Selected Text",
		defaultValue: "#FFFFFF",
	},
	defaultCountry: {
		type: ControlType.Enum,
		title: "Default Country",
		options: countries.map((c) => c.code),
		optionTitles: countries.map((c) => `${c.flag} ${c.name} ${c.prefix}`),
		defaultValue: "US",
	},
	placeholder: {
		type: ControlType.String,
		title: "Placeholder",
		defaultValue: "Phone number",
	},
	ariaLabelInput: {
		type: ControlType.String,
		title: "Input ARIA Label",
		defaultValue: "Phone number input",
	},
	ariaLabelSelect: {
		type: ControlType.String,
		title: "Select ARIA Label",
		defaultValue: "Country code selector",
	},
	useCustomCSV: {
		type: ControlType.Boolean,
		title: "Custom Countries",
		defaultValue: false,
		enabledTitle: "CSV File",
		disabledTitle: "Default",
	},
	csvFile: {
		type: ControlType.File,
		title: "CSV File",
		allowedFileTypes: ["csv"],
		hidden: ({ useCustomCSV }) => !useCustomCSV,
	},
});

// virtual:phone-number-input
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			<PhoneNumberInput suppressHydrationWarning={true} {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PhoneNumberInputFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={PhoneNumberInput}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, PhoneNumberInput);
var phone_number_input_default = ComponentWithRoot;
export { phone_number_input_default as default };
