// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d9b75cbdeaeee319 "Builtric", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Procurement' | 'Finance' | 'Management' | 'HSE' | 'Data' | 'Primary Mobile' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-HMI5HUCM.js";

// virtual:procurement-tile
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tkxcEYf5n0O72MzW67nO/C8OUAhh54DZORnOIGZ1L/RdvVTjTYE.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = [
	"qw8Fh6hBn",
	"PK56O9SYp",
	"bfZ3xAEhV",
	"KGy85IvdS",
	"dWS2Do8N5",
	"T7GmzXn4M",
];
var serializationHash = "framer-Fq2WN";
var variantClassNames = {
	bfZ3xAEhV: "framer-v-1jfwa5h",
	dWS2Do8N5: "framer-v-cxtawo",
	KGy85IvdS: "framer-v-17pbr7m",
	PK56O9SYp: "framer-v-rqi5v8",
	qw8Fh6hBn: "framer-v-a04f9k",
	T7GmzXn4M: "framer-v-1anbwmf",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Primary Mobile": "T7GmzXn4M",
	Data: "dWS2Do8N5",
	Finance: "PK56O9SYp",
	HSE: "KGy85IvdS",
	Management: "bfZ3xAEhV",
	Procurement: "qw8Fh6hBn",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "qw8Fh6hBn",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "qw8Fh6hBn",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-a04f9k",
							className,
							classNames,
						)}
						data-framer-name={"Procurement"}
						layoutDependency={layoutDependency}
						layoutId={"qw8Fh6hBn"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								bfZ3xAEhV: {
									"data-framer-name": "Management",
								},
								dWS2Do8N5: {
									"data-framer-name": "Data",
								},
								KGy85IvdS: {
									"data-framer-name": "HSE",
								},
								PK56O9SYp: {
									"data-framer-name": "Finance",
								},
								T7GmzXn4M: {
									"data-framer-name": "Primary Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							suppressHydrationWarning={true}
							background={{
								alt: "",
								fit: "fill",
								sizes: componentViewport?.width || "100vw",
							}}
							className={"framer-1nr5l1s"}
							layoutDependency={layoutDependency}
							layoutId={"qbPWzChD4"}
							{...addPropertyOverrides(
								{
									T7GmzXn4M: {
										background: {
											alt: "",
											fit: "fill",
											sizes: "99px",
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1oboqa2"}
							layoutDependency={layoutDependency}
							layoutId={"IYgUmLeUe"}
						>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-z2jk8x"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"KiezRw4pl"}
								style={{
									"--extracted-gdpscs": "rgb(99, 99, 99)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										bfZ3xAEhV: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														style={{
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "8px",
															"--framer-line-height": "1.3em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(99, 99, 99))",
														}}
													>
														{"Project Management"}
													</motion.h1>
												</React.Fragment>
											),
										},
										dWS2Do8N5: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														style={{
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "8px",
															"--framer-line-height": "1.3em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(99, 99, 99))",
														}}
													>
														{"Data Management"}
													</motion.h1>
												</React.Fragment>
											),
										},
										KGy85IvdS: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														style={{
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "8px",
															"--framer-line-height": "1.3em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(99, 99, 99))",
														}}
													>
														{"HSE"}
													</motion.h1>
												</React.Fragment>
											),
										},
										PK56O9SYp: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														style={{
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "8px",
															"--framer-line-height": "1.3em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(99, 99, 99))",
														}}
													>
														{"Finance"}
													</motion.h1>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h1
										suppressHydrationWarning={true}
										style={{
											"--framer-font-open-type-features":
												"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
											"--framer-font-size": "8px",
											"--framer-line-height": "1.3em",
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-gdpscs, rgb(99, 99, 99))",
										}}
									>
										{"Contracts"}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-1vor0e9"}
								fonts={["Inter-SemiBold"]}
								layoutDependency={layoutDependency}
								layoutId={"ZDMyQLjWo"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										bfZ3xAEhV: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "18px",
															"--framer-font-weight": "600",
															"--framer-letter-spacing": "-0.04em",
															"--framer-line-height": "1em",
															"--framer-text-alignment": "left",
														}}
													>
														{"Progress and Inspections"}
													</motion.h1>
												</React.Fragment>
											),
										},
										dWS2Do8N5: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "18px",
															"--framer-font-weight": "600",
															"--framer-letter-spacing": "-0.04em",
															"--framer-line-height": "1em",
															"--framer-text-alignment": "left",
														}}
													>
														{"Store and Organise Data Seamlessly"}
													</motion.h1>
												</React.Fragment>
											),
										},
										KGy85IvdS: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "18px",
															"--framer-font-weight": "600",
															"--framer-letter-spacing": "-0.04em",
															"--framer-line-height": "1em",
															"--framer-text-alignment": "left",
														}}
													>
														{"Health ,Safety and Environmental Management"}
													</motion.h1>
												</React.Fragment>
											),
										},
										PK56O9SYp: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "18px",
															"--framer-font-weight": "600",
															"--framer-letter-spacing": "-0.04em",
															"--framer-line-height": "1em",
															"--framer-text-alignment": "left",
														}}
													>
														{"Financial Tracking and Payments"}
													</motion.h1>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h1
										suppressHydrationWarning={true}
										style={{
											"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
											"--framer-font-open-type-features":
												"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
											"--framer-font-size": "18px",
											"--framer-font-weight": "600",
											"--framer-letter-spacing": "-0.04em",
											"--framer-line-height": "1em",
											"--framer-text-alignment": "left",
										}}
									>
										{"Procurements and Contracts "}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<RichText
								suppressHydrationWarning={true}
								__fromCanvasComponent={true}
								className={"framer-1nyffsa"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Ah5AeJjPn"}
								style={{
									"--extracted-gdpscs": "rgb(99, 99, 99)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										bfZ3xAEhV: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														dir={"auto"}
														style={{
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "12px",
															"--framer-line-height": "1.3em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(99, 99, 99))",
														}}
													>
														{
															"Track work completion and submit inspection requests instantly."
														}
													</motion.h1>
												</React.Fragment>
											),
										},
										dWS2Do8N5: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														dir={"auto"}
														style={{
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "12px",
															"--framer-line-height": "1.3em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(99, 99, 99))",
														}}
													>
														{
															"Store and organise project files and records with consistent version control and data integrity."
														}
													</motion.h1>
												</React.Fragment>
											),
										},
										KGy85IvdS: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														style={{
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "12px",
															"--framer-line-height": "1.3em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(99, 99, 99))",
														}}
													>
														{
															"Conduct inspections, record findings and generate reports."
														}
													</motion.h1>
												</React.Fragment>
											),
										},
										PK56O9SYp: {
											children: (
												<React.Fragment>
													<motion.h1
														suppressHydrationWarning={true}
														style={{
															"--framer-font-open-type-features":
																"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
															"--framer-font-size": "12px",
															"--framer-line-height": "1.3em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(99, 99, 99))",
														}}
													>
														{
															"Generate certificates and monitor cash flow in real time."
														}
													</motion.h1>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h1
										suppressHydrationWarning={true}
										dir={"auto"}
										style={{
											"--framer-font-open-type-features":
												"'cv01' on, 'cv09' on, 'cv11' on, 'cv05' on, 'ss03' on",
											"--framer-font-size": "12px",
											"--framer-line-height": "1.3em",
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-gdpscs, rgb(99, 99, 99))",
										}}
									>
										{
											"Create and manage purchase orders with precision and control."
										}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1unx81u"}
								layoutDependency={layoutDependency}
								layoutId={"SHRsMFw5Z"}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Fq2WN.framer-t4k904, .framer-Fq2WN .framer-t4k904 { display: block; }",
	".framer-Fq2WN.framer-a04f9k { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: 268px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
	".framer-Fq2WN .framer-1nr5l1s { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 112px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: auto; will-change: var(--framer-will-change-filter-override, filter); }",
	".framer-Fq2WN .framer-1oboqa2 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 12px; position: relative; width: 206px; }",
	".framer-Fq2WN .framer-z2jk8x { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-Fq2WN .framer-1vor0e9, .framer-Fq2WN .framer-1nyffsa { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-Fq2WN .framer-1unx81u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; min-height: 22px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-Fq2WN.framer-v-1anbwmf.framer-a04f9k { flex-direction: row; height: min-content; width: 378px; }",
	".framer-Fq2WN.framer-v-1anbwmf .framer-1nr5l1s { height: auto; width: 99px; }",
	".framer-Fq2WN.framer-v-1anbwmf .framer-1oboqa2 { flex: 1 0 0px; width: 1px; }",
];
var FramerRdvVTjTYE = withCSS(Component, css, "framer-Fq2WN");
var stdin_default = FramerRdvVTjTYE;
FramerRdvVTjTYE.displayName = "Procurement Tile";
FramerRdvVTjTYE.defaultProps = {
	height: 268,
	width: 206,
};
addPropertyControls(FramerRdvVTjTYE, {
	variant: {
		options: [
			"qw8Fh6hBn",
			"PK56O9SYp",
			"bfZ3xAEhV",
			"KGy85IvdS",
			"dWS2Do8N5",
			"T7GmzXn4M",
		],
		optionTitles: [
			"Procurement",
			"Finance",
			"Management",
			"HSE",
			"Data",
			"Primary Mobile",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerRdvVTjTYE,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/yDtI2UI8XcEg1W2je9XPN3Noo.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:procurement-tile
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProcurementTileFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var procurement_tile_default = ComponentWithRoot;
export { procurement_tile_default as default };
