// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d9b75cbdeaeee319 "Builtric", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-HMI5HUCM.js";

// virtual:scroll
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/30S3p6yoZPyErYZ1YTme/QcuyrVFvVc38cSo2bcfZ/IW2njtJyr.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	CycleVariantState,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["lEDffK99z", "FwepaKf8r"];
var serializationHash = "framer-6Xpv6";
var variantClassNames = {
	FwepaKf8r: "framer-v-diby1r",
	lEDffK99z: "framer-v-wd1xo4",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "lEDffK99z",
	Variant: "FwepaKf8r",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "lEDffK99z",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "lEDffK99z",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppearabapei = activeVariantCallback(async (...args) => {
		setVariant(CycleVariantState, true);
	});
	useOnVariantChange(baseVariant, {
		default: onAppearabapei,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-wd1xo4",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"lEDffK99z"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-8969991b-438f-4d85-93dd-14578be35b6e, rgb(255, 219, 52))",
							borderBottomLeftRadius: 21,
							borderBottomRightRadius: 21,
							borderTopLeftRadius: 21,
							borderTopRightRadius: 21,
							...style,
						}}
						{...addPropertyOverrides(
							{
								FwepaKf8r: {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<SVG
							suppressHydrationWarning={true}
							className={"framer-xqs6dz"}
							layoutDependency={layoutDependency}
							layoutId={"QdD84CTrg"}
							requiresOverflowVisible={false}
							svg={
								'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 14 14" overflow="visible"><path d="M 7 0 C 10.866 0 14 3.134 14 7 C 14 10.866 10.866 14 7 14 C 3.134 14 0 10.866 0 7 C 0 3.134 3.134 0 7 0 Z" fill="var(--token-7eaeceec-39c4-4a6d-bc25-34b9a3c7aa26, rgb(33, 38, 44)) /* {&quot;name&quot;:&quot;Primary black&quot;} */"></path></svg>'
							}
							withExternalLayout={true}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6Xpv6.framer-1f946gh, .framer-6Xpv6 .framer-1f946gh { display: block; }",
	".framer-6Xpv6.framer-wd1xo4 { height: 58px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 36px; will-change: var(--framer-will-change-override, transform); }",
	".framer-6Xpv6 .framer-xqs6dz { height: 14px; left: 11px; position: absolute; top: 8px; width: 14px; }",
	".framer-6Xpv6.framer-v-diby1r .framer-xqs6dz { top: 38px; }",
];
var FramerIW2njtJyr = withCSS(Component, css, "framer-6Xpv6");
var stdin_default = FramerIW2njtJyr;
FramerIW2njtJyr.displayName = "Scroll";
FramerIW2njtJyr.defaultProps = {
	height: 58,
	width: 36,
};
addPropertyControls(FramerIW2njtJyr, {
	variant: {
		options: ["lEDffK99z", "FwepaKf8r"],
		optionTitles: ["Variant 1", "Variant"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerIW2njtJyr,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:scroll
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ScrollFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var scroll_default = ComponentWithRoot;
export { scroll_default as default };
