// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d9b75cbdeaeee319 "Builtric", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant' | 'Variant' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-HMI5HUCM.js";

// virtual:scroll-indicator
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/VwoKDcKrdckSgdj1HTH8/ibSKukSrt6B9u4DsenGt/aMFrwz7CL.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	CycleVariantState,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["B3qXe0MjJ", "kmLcu1D5m", "t2AMQ7WvG"];
var serializationHash = "framer-azvzw";
var variantClassNames = {
	B3qXe0MjJ: "framer-v-1g1wdwk",
	kmLcu1D5m: "framer-v-dnv7la",
	t2AMQ7WvG: "framer-v-1jeae1j",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.7,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "B3qXe0MjJ",
	Variant: "t2AMQ7WvG",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "B3qXe0MjJ",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "B3qXe0MjJ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppearws8ebg = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState, true), 500);
	});
	const onAppear1yp0wpv = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState, true), 1e3);
	});
	useOnVariantChange(baseVariant, {
		default: onAppearws8ebg,
		t2AMQ7WvG: onAppear1yp0wpv,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1g1wdwk",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"B3qXe0MjJ"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								kmLcu1D5m: {
									"data-framer-name": void 0,
								},
								t2AMQ7WvG: {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<SVG
							suppressHydrationWarning={true}
							className={"framer-1xee0p8"}
							layoutDependency={layoutDependency}
							layoutId={"bCsaCaEQg"}
							requiresOverflowVisible={true}
							svg={
								'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 34 33" overflow="visible"><g><defs><path d="M 0 5 C 0 2.239 2.239 0 5 0 L 29 0 C 31.761 0 34 2.239 34 5 L 34 28 C 34 30.761 31.761 33 29 33 L 5 33 C 2.239 33 0 30.761 0 28 Z" id="a1284z"></path><filter id="a1304z" filterUnits="objectBoundingBox" x="-49.4%" y="-53.9%" width="198.8%" height="207.9%"><feOffset dx="0" dy="1" in="SourceAlpha" result="a1307z"></feOffset><feGaussianBlur stdDeviation="4" in="a1307z" result="a1308z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1309z"></feFlood><feComposite in="a1309z" in2="a1308z" operator="in" result="a1305z"></feComposite></filter></defs><mask id="a1306z" x="-49.4%" y="-53.9%" width="198.8%" height="207.9%"><rect x="-49.4%" y="-53.9%" width="198.8%" height="207.9%" fill="white"></rect><use href="#a1284z" fill="black"></use></mask><g filter="url(#a1304z)" mask="url(#a1306z)"><use fill="black" stroke="black" stroke-opacity="0" stroke-width="0" xlink:href="#a1284z" clip-path="url(#a1285z)"></use></g><use xlink:href="#a1284z" fill="var(--token-8969991b-438f-4d85-93dd-14578be35b6e, rgb(255, 219, 52)) /* {&quot;name&quot;:&quot;Hero Yellow&quot;} */" clip-path="url(#a1285z)"></use></g></svg>'
							}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									kmLcu1D5m: {
										svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 34 33" overflow="visible"><g><defs><path d="M 0 5 C 0 2.239 2.239 0 5 0 L 29 0 C 31.761 0 34 2.239 34 5 L 34 28 C 34 30.761 31.761 33 29 33 L 5 33 C 2.239 33 0 30.761 0 28 Z" id="a1286z"></path><filter id="a1310z" filterUnits="objectBoundingBox" x="-49.4%" y="-53.9%" width="198.8%" height="207.9%"><feOffset dx="0" dy="1" in="SourceAlpha" result="a1313z"></feOffset><feGaussianBlur stdDeviation="4" in="a1313z" result="a1314z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1315z"></feFlood><feComposite in="a1315z" in2="a1314z" operator="in" result="a1311z"></feComposite></filter></defs><mask id="a1312z" x="-49.4%" y="-53.9%" width="198.8%" height="207.9%"><rect x="-49.4%" y="-53.9%" width="198.8%" height="207.9%" fill="white"></rect><use href="#a1286z" fill="black"></use></mask><g filter="url(#a1310z)" mask="url(#a1312z)"><use fill="black" stroke="black" stroke-opacity="0" stroke-width="0" xlink:href="#a1286z" clip-path="url(#a1287z)"></use></g><use xlink:href="#a1286z" fill="var(--token-8969991b-438f-4d85-93dd-14578be35b6e, rgb(255, 219, 52)) /* {&quot;name&quot;:&quot;Hero Yellow&quot;} */" clip-path="url(#a1287z)"></use></g></svg>',
									},
									t2AMQ7WvG: {
										svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 34 33" overflow="visible"><g><defs><path d="M 0 5 C 0 2.239 2.239 0 5 0 L 29 0 C 31.761 0 34 2.239 34 5 L 34 28 C 34 30.761 31.761 33 29 33 L 5 33 C 2.239 33 0 30.761 0 28 Z" id="a1294z"></path><filter id="a1316z" filterUnits="objectBoundingBox" x="-49.4%" y="-53.9%" width="198.8%" height="207.9%"><feOffset dx="0" dy="1" in="SourceAlpha" result="a1319z"></feOffset><feGaussianBlur stdDeviation="4" in="a1319z" result="a1320z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1321z"></feFlood><feComposite in="a1321z" in2="a1320z" operator="in" result="a1317z"></feComposite></filter></defs><mask id="a1318z" x="-49.4%" y="-53.9%" width="198.8%" height="207.9%"><rect x="-49.4%" y="-53.9%" width="198.8%" height="207.9%" fill="white"></rect><use href="#a1294z" fill="black"></use></mask><g filter="url(#a1316z)" mask="url(#a1318z)"><use fill="black" stroke="black" stroke-opacity="0" stroke-width="0" xlink:href="#a1294z" clip-path="url(#a1295z)"></use></g><use xlink:href="#a1294z" fill="var(--token-8969991b-438f-4d85-93dd-14578be35b6e, rgb(255, 219, 52)) /* {&quot;name&quot;:&quot;Hero Yellow&quot;} */" clip-path="url(#a1295z)"></use></g></svg>',
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
						<SVG
							suppressHydrationWarning={true}
							className={"framer-1k2ajgk"}
							layoutDependency={layoutDependency}
							layoutId={"LkkNL1mGX"}
							requiresOverflowVisible={true}
							svg={
								'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 19 8.63" overflow="visible"><g><path d="M 9.5 8 L 9.289 8.485" fill="transparent" stroke-width="2" stroke="var(--token-7eaeceec-39c4-4a6d-bc25-34b9a3c7aa26, rgb(33, 38, 44)) /* {&quot;name&quot;:&quot;Primary black&quot;} */"></path><path d="M 0 0 L 9.5 8.63 L 19 0" fill="transparent" stroke-width="2" stroke="var(--token-7eaeceec-39c4-4a6d-bc25-34b9a3c7aa26, rgb(33, 38, 44)) /* {&quot;name&quot;:&quot;Primary black&quot;} */"></path></g></svg>'
							}
							withExternalLayout={true}
						>
							<SVG
								suppressHydrationWarning={true}
								className={"framer-ebzgsb"}
								layoutDependency={layoutDependency}
								layoutId={"OznZdi7ti"}
								requiresOverflowVisible={true}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1 1" overflow="visible"><path d="M 0.211 0 L 0 0.485" fill="transparent" stroke-width="2" stroke="var(--token-7eaeceec-39c4-4a6d-bc25-34b9a3c7aa26, rgb(33, 38, 44)) /* {&quot;name&quot;:&quot;Primary black&quot;} */"></path></svg>'
								}
								withExternalLayout={true}
							/>
							<SVG
								suppressHydrationWarning={true}
								className={"framer-o1ri7n"}
								layoutDependency={layoutDependency}
								layoutId={"NAz1wITtt"}
								requiresOverflowVisible={true}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 19 8.63" overflow="visible"><path d="M 0 0 L 9.5 8.63 L 19 0" fill="transparent" stroke-width="2" stroke="var(--token-7eaeceec-39c4-4a6d-bc25-34b9a3c7aa26, rgb(33, 38, 44)) /* {&quot;name&quot;:&quot;Primary black&quot;} */"></path></svg>'
								}
								withExternalLayout={true}
							/>
						</SVG>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-azvzw.framer-ic0bpq, .framer-azvzw .framer-ic0bpq { display: block; }",
	".framer-azvzw.framer-1g1wdwk { height: 40px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 44px; }",
	".framer-azvzw .framer-1xee0p8 { height: 33px; left: 5px; position: absolute; top: 3px; width: 34px; }",
	".framer-azvzw .framer-1k2ajgk { height: 9px; left: 13px; position: absolute; top: 8px; width: 19px; }",
	".framer-azvzw .framer-ebzgsb { height: 1px; left: 10px; position: absolute; top: 8px; width: 1px; }",
	".framer-azvzw .framer-o1ri7n { height: 9px; left: 0px; position: absolute; top: 0px; width: 19px; }",
	".framer-azvzw.framer-v-dnv7la .framer-1k2ajgk { top: 22px; }",
];
var FrameraMFrwz7CL = withCSS(Component, css, "framer-azvzw");
var stdin_default = FrameraMFrwz7CL;
FrameraMFrwz7CL.displayName = "Scroll indicator";
FrameraMFrwz7CL.defaultProps = {
	height: 40,
	width: 44,
};
addPropertyControls(FrameraMFrwz7CL, {
	variant: {
		options: ["B3qXe0MjJ", "kmLcu1D5m", "t2AMQ7WvG"],
		optionTitles: ["Variant 1", "Variant", "Variant"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FrameraMFrwz7CL,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:scroll-indicator
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "B3qXe0MjJ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ScrollIndicatorFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var scroll_indicator_default = ComponentWithRoot;
export { scroll_indicator_default as default };
