// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d9b75cbdeaeee319 "Builtric", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Closed' | 'Open' // Variant
 * hover?: Function // Hover
 * title?: string // Title
 * onDAPvjrdfGCHange?: any // onDAPvjrdfGCHange
}} Props

 */
import { stdin_default } from "./chunks/chunk-KUR7NEVD.js";
import { routes } from "./chunks/chunk-HMI5HUCM.js";

// virtual:trigger
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/85ghWpP0tWqkmGknTIgP/XuBibQ2Ke0xl7doE1tYd/eygufveO4.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var CaretFonts = getFonts(stdin_default);
var cycleOrder = ["AnYVkMkbA", "JzjL7yc7R"];
var serializationHash = "framer-RMTzv";
var variantClassNames = {
	AnYVkMkbA: "framer-v-119u96q",
	JzjL7yc7R: "framer-v-ww8lli",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Closed: "AnYVkMkbA",
	Open: "JzjL7yc7R",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, hover, id, title, width, ...props }) => {
	return {
		...props,
		DApvjrdfG: title ?? props.DApvjrdfG ?? "Product",
		PWSlWeqS6: hover ?? props.PWSlWeqS6,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "AnYVkMkbA",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		PWSlWeqS6: PWSlWeqS62,
		DApvjrdfG: DApvjrdfG2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "AnYVkMkbA",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter170i0h9 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		if (PWSlWeqS62) {
			const res = await PWSlWeqS62(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-119u96q",
							className,
							classNames,
						)}
						data-framer-name={"Closed"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"AnYVkMkbA"}
						onMouseEnter={onMouseEnter170i0h9}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								JzjL7yc7R: {
									"data-framer-name": "Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							suppressHydrationWarning={true}
							__fromCanvasComponent={true}
							className={"framer-cwmlr5"}
							fonts={["Inter-Medium"]}
							layoutDependency={layoutDependency}
							layoutId={"SXTq5Q9XQ"}
							style={{
								"--extracted-r6o4lv": "rgb(68, 68, 68)",
								"--framer-paragraph-spacing": "0px",
							}}
							text={DApvjrdfG2}
							variants={{
								JzjL7yc7R: {
									"--extracted-r6o4lv": "rgb(136, 136, 136)",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									JzjL7yc7R: {
										children: (
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													style={{
														"--font-selector": "SW50ZXItTWVkaXVt",
														"--framer-font-size": "15px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "-0.01em",
														"--framer-line-height": "2em",
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, rgb(136, 136, 136))",
													}}
												>
													{"Product"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									suppressHydrationWarning={true}
									style={{
										"--font-selector": "SW50ZXItTWVkaXVt",
										"--framer-font-size": "15px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "-0.01em",
										"--framer-line-height": "2em",
										"--framer-text-alignment": "left",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(68, 68, 68))",
									}}
								>
									{"Product"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<ComponentViewportProvider suppressHydrationWarning={true}>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-1i9nlp1-container"}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"TUKCPfyve-container"}
								nodeId={"TUKCPfyve"}
								rendersWithMotion={true}
								scopeId={"eygufveO4"}
							>
								{_jsx(stdin_default, {
									suppressHydrationWarning: true,
									height: "100%",
									id: "TUKCPfyve",
									layoutId: "TUKCPfyve",
									variant: matchVariant("wnipua7N_"),
									width: "100%",
									...addPropertyOverrides(
										{
											JzjL7yc7R: {
												variant: matchVariant("BJYJhvClj"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RMTzv.framer-qiee1v, .framer-RMTzv .framer-qiee1v { display: block; }",
	".framer-RMTzv.framer-119u96q { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: center; overflow: hidden; padding: 5px 0px 5px 0px; position: relative; width: min-content; }",
	".framer-RMTzv .framer-cwmlr5 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-RMTzv .framer-1i9nlp1-container { flex: none; height: auto; position: relative; width: auto; }",
];
var FramereygufveO4 = withCSS(Component, css, "framer-RMTzv");
var stdin_default2 = FramereygufveO4;
FramereygufveO4.displayName = "Trigger";
FramereygufveO4.defaultProps = {
	height: 40,
	width: 74,
};
addPropertyControls(FramereygufveO4, {
	variant: {
		options: ["AnYVkMkbA", "JzjL7yc7R"],
		optionTitles: ["Closed", "Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	PWSlWeqS6: {
		title: "Hover",
		type: ControlType.EventHandler,
	},
	DApvjrdfG: {
		defaultValue: "Product",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	onDApvjrdfGChange: {
		changes: "DApvjrdfG",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramereygufveO4,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
			],
		},
		...CaretFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramereygufveO4.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:trigger
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TriggerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"d9b75cbdeaeee3198b6540fd7e4e4ad7914f2cf01c2adcb4266c0b2304f77263"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var trigger_default = ComponentWithRoot;
export { trigger_default as default };
